In [1]:
import torch

In [2]:
x = torch.tensor([[1.0, 2.0, 3.0,4.0]])
x,x.shape

(tensor([[1., 2., 3., 4.]]), torch.Size([1, 4]))

In [3]:
x.view(2,2),x.reshape(2,2)

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[1., 2.],
         [3., 4.]]))

In [4]:
torch.permute(x, (1,0)).shape#重新排列维度

torch.Size([4, 1])

In [5]:
x.shape,x.unsqueeze(1).shape#增加张量维度

(torch.Size([1, 4]), torch.Size([1, 1, 4]))

In [6]:
x.transpose(0,1).shape#交换维度

torch.Size([4, 1])

In [11]:
x.expand(4,4)#扩展张量

tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])

In [29]:

y = torch.tril(torch.ones(4,4,dtype=torch.bool),diagonal=0)#下三角矩阵
y,~y

(tensor([[ True, False, False, False],
         [ True,  True, False, False],
         [ True,  True,  True, False],
         [ True,  True,  True,  True]]),
 tensor([[False,  True,  True,  True],
         [False, False,  True,  True],
         [False, False, False,  True],
         [False, False, False, False]]))

In [26]:
y.unsqueeze(0).unsqueeze(0).shape

torch.Size([1, 1, 4, 4])

In [33]:
a = torch.ones_like(y,dtype=torch.float32)
a.masked_fill(~y,float('-inf'))

tensor([[1., -inf, -inf, -inf],
        [1., 1., -inf, -inf],
        [1., 1., 1., -inf],
        [1., 1., 1., 1.]])

In [5]:
import numpy as np
# 加载npy文件
data = np.load('C:/Users/86157/Desktop/machine-1-3_labels.npy')
print(data)
# 查看数据类型与形状
print(f"Data type: {data.dtype}")
print(f"Data shape: {data.shape}")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Data type: float64
Data shape: (23703, 38)


In [6]:
import numpy as np
# 加载npy文件
data = np.load('C:/Users/86157/Desktop/machine-1-3_test.npy')
print(data)
# 查看数据类型与形状
print(f"Data type: {data.dtype}")
print(f"Data shape: {data.shape}")

[[2.42424e-01 1.39060e-02 1.49130e-02 ... 6.35967e-01 0.00000e+00
  0.00000e+00]
 [2.42424e-01 1.38500e-02 1.47890e-02 ... 6.09756e-01 0.00000e+00
  0.00000e+00]
 [2.22222e-01 1.39060e-02 1.49750e-02 ... 6.10120e-01 0.00000e+00
  0.00000e+00]
 ...
 [1.01010e-02 1.39100e-03 7.46000e-04 ... 1.09200e-03 0.00000e+00
  0.00000e+00]
 [1.01010e-02 7.23000e-04 6.21000e-04 ... 7.28000e-04 0.00000e+00
  0.00000e+00]
 [1.01010e-02 1.44600e-03 8.08000e-04 ... 7.28000e-04 0.00000e+00
  0.00000e+00]]
Data type: float64
Data shape: (23703, 38)


In [7]:
import numpy as np
# 加载npy文件
data = np.load('C:/Users/86157/Desktop/machine-1-3_train.npy')
print(data)
# 查看数据类型与形状
print(f"Data type: {data.dtype}")
print(f"Data shape: {data.shape}")

[[0.080808 0.003671 0.003107 ... 0.162359 0.       0.      ]
 [0.070707 0.003337 0.003169 ... 0.15253  0.       0.      ]
 [0.060606 0.003449 0.003231 ... 0.140153 0.       0.      ]
 ...
 [0.232323 0.013016 0.014106 ... 0.610484 0.       0.      ]
 [0.242424 0.014573 0.015038 ... 0.633418 0.       0.      ]
 [0.242424 0.011347 0.014292 ... 0.637423 0.       0.      ]]
Data type: float64
Data shape: (23702, 38)
